### ISSUE TITLE
add Linux support

### ISSUE THREAD

**Issue by droundy** [smacdo/screenlocker#1]
You could copy the principles from https://lib.rs/crates/lock

**Comment by smacdo** [comment]
I believe the linked pull request should work, but I don't have a machine with Fedora/Ubuntu/etc desktop lying around. I could install fedora on a spare laptop in a few days, but if you're feeling adventurous give the PR a shot and let me know if it works for you.

**Comment by smacdo** [comment]
Verified working on Fedora Core 36
