### ISSUE TITLE
issue release with lib target

### ISSUE THREAD

**Issue by droundy** [smacdo/screenlocker#2]
see above, can't use this crate

**Comment by smacdo** [comment]
Can you elaborate more on your issue? I'm somewhat new to publishing crates with Rust, so I'm not quite sure what you mean by this issue. Do you mean creating a git tag to track a stable release? Or is there an issue with consuming the crate as a library from another rust project?

**Comment by droundy** [comment]
See https://doc.rust-lang.org/cargo/reference/cargo-targets.html

You need to create a library target in order for me to use your package as a library.

BTW I'm frequently writing with baby in arms, hence my terseness, not meant to be brusque or ride t...

**Comment by smacdo** [comment]
I appreciate the clarification, terseness can be easily misinterpreted online. I'm impressed you are still filing issues with a baby on your arm! I remember those days - they were quite exhausting.

So according to the doc you linked, looks like I need to add something like the following to `Cargo.toml`. I'm guessing toml allows for empty sections although I confirm that on my box later.

```
[lib]

[[bin]]
name = "screenlocker"
```

**Comment by droundy** [comment]
Something like that. I usually copy one of my older ones... and I suppose you could also copy one of my older ones, since they're public also...
